apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-j55a
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-j55a
    app.kubernetes.io/part-of: ci10t-777-0071-app
  name: devfile-sample-j55a
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-j55a
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-j55a
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0071-tenant/ci10t-777-0071-app/devfile-sample-j55a@sha256:c468d01ce7139ce36faa2191e7b523420c3ed8cba4ad03b2d7e8399e1dca5bf9
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
